### ISSUE TITLE
Resetting observations and server.path

### ISSUE THREAD

**Issue by brbeaird** [fauria/wunderground-pws#1]
I'm not sure if I'm doing something wrong, but I've noticed if I send observations once, everything works great. However, if I send a new set of observations a few minutes later, the resulting query string being sent to Wunderground contains both sets of observations. This seems to be because while the observation payload is cleared each time, server.path is never cleared and instead ends up perpetually concatenating each observation together.

Any thoughts on that?

**Comment by fauria** [comment]
Released version 1.3.2 after merging PR#2.
